### ISSUE TITLE
A PATCH is neither safe nor idempotent as defined by [RFC2616]

### ISSUE THREAD

**Issue by easterwood** [spring-guides/understanding#17]
In the section [PATCH](https://spring.io/understanding/REST#patch) a PATCH request is described as `idempotent` but according to the [RFC2616](https://tools.ietf.org/html/rfc5789) it isn't.

![image](https://user-images.githubusercontent.com/7085240/42228507-7249a9f2-7ee4-11e8-9870-9febb03fde97.png)

What is correct?

**Comment by gregturn** [comment]
I believe this was a copy-paste error.
